from pydantic import BaseModel, Field


class ResponseOutput(BaseModel):
    """
    Output model representing the response generated by the AI system.

    Attributes:
        response (str): The AI-generated response to the user's question.
        session_id (str): Unique identifier for the session.
        user_id (str): Unique identifier for the user.
    """

    response: str = Field(description="The AI-generated response to the user's input.")
    session_id: str = Field(description="Unique identifier for the current session.")
    user_id: str = Field(description="Unique identifier for the user.")
